### ISSUE TITLE
unable to open script file board_mele.fex

### ISSUE THREAD

**Issue by a740122** [haotseng/auto_build_cubieboard#1]
[Copy UBoot binary..]
argc = 2
input name /home/cl/mycompile/auto_build_cubieboard/output_cb4/uboot/board_mele.fex
Script 1 source file Path=/home/cl/mycompile/auto_build_cubieboard//home/cl/mycompile/auto_build_cubieboard/output_cb4/uboot/board_mele.fex
Script 1 bin file Path=/home/cl/mycompile/auto_build_cubieboard//home/cl/mycompile/auto_build_cubieboard/output_cb4/uboot/board_mele.bin
unable to open script file /home/cl/mycompile/auto_build_cubieboard//home/cl/mycompile/auto_build_cubieboard/output_cb4/uboot/board_mele.fex
Error !! Can't generate /home/cl/mycompile/auto_build_cubieboard/output_cb4/uboot/board_mele.bin file

**Comment by haotseng** [comment]
The "board_mele.bin" file generated by running the command "script board_mele.fex".
The  "script" binary file located in  "cb4_uboot_bin/tools" directory. Please make sure this file has executable attribute. And the board_mele.fex must be DOS format text file. Not UNIX format text file.

**Comment by haotseng** [comment]
The "cb4_uboot_bin/tools/script" is a binary file, that come from Allwinner A80 SDK package. I didn't have the source code. It can convert the FEX file to BIN file that need by A80 u-boot.

**Comment by haotseng** [comment]
I found these three binary files  "script, update_boot0, update_uboot" seems can't work well when using full path for arguments. I modified the cb4_prepare_uboot.sh to fixed the problem. It should be okay to avoid the "path" problem.
