### ISSUE TITLE
How can I add linux-headers?

### ISSUE THREAD

**Issue by a740122** [haotseng/auto_build_cubieboard#2]
dahdi-linux compile need linux-headers, but not have.

**Comment by haotseng** [comment]
As I know, there is no linux-header package for cubieboard baord. We only can get  linux kernel source from [CB1,CB2, CB3 kernel source](https://github.com/linux-sunxi/linux-sunxi) and [CB4 kernel source](https://github.com/cubieboard/CC-A80-kernel-source). 

So, if you want build your special driver, you can  merge the driver source into kernel source. Then build the kernel again with your special driver.

**Comment by a740122** [comment]
It's not very friendly that merge the driver source into kernel source.
Can I use kernel source path for build special driver?

**Comment by haotseng** [comment]
It's seems not work by using kernel source' header file. Because some headers are different between  kernel header package and kernel source' header.
