### ISSUE TITLE
run update_uboot_to_disk_images.sh but Can't found output_cb4/uboot/boot.cmd

### ISSUE THREAD

**Issue by a740122** [haotseng/auto_build_cubieboard#3]
run cmd
sudo ./update_uboot_to_disk_images.sh img cb4-debian-server-hdmi-card-v1.0.img output_cb4/uboot

and
Can't found output_cb4/uboot/boot.cmd

**Comment by haotseng** [comment]
Try:
sudo ./update_uboot_to_disk_images.sh img cb4-debian-server-hdmi-card-v1.0.img ./output_cb4/uboot

**Comment by haotseng** [comment]
If you use Cubieboard4 (CC-A80), please use "cb4_update_uboot_to_disk_images.sh" instean of "update_uboot_to_disk_images.sh"
